name: Contributors

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
#  package-json:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: wow-actions/update-contributors@v1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          affiliation: all
#          commit_message: "chore: Update Collaborators, Contributors etc. in package.json"
#  readme:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - uses: akhilmhdh/contributors-readme-action@v2.2
#        with:
#          collaborators: all
#          commit_message: "chore: Update Collaborators, Contributors etc. in README"
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Post WebHook Message
        run: |
          curl -L --output ./discord.sh https://raw.githubusercontent.com/ChaoticWeg/discord.sh/master/discord.sh
          chmod a+x ./discord.sh
          ./discord.sh \
            --webhook-url="${{ secrets.WEBHOOK_URL }}" \
            --username "$GITHUB_REPOSITORY" \
            --avatar "https://i.griefed.de/images/2020/11/18/Prosper_Docker_300x300.png" \
            --text "There's been a new release for $GITHUB_REPOSITORY. The new version is $GITHUB_REF_NAME and is available at <$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/$GITHUB_REF_NAME>" \
            --title "New $GITHUB_REPOSITORY Release" \
            --description "There's been a new release for $GITHUB_REPOSITORY. The new version is $GITHUB_REF_NAME and is available at $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/$GITHUB_REF_NAME" \
            --color "0xC0FFEE" \
            --url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/$GITHUB_REF_NAME" \
            --author "Griefed" \
            --author-url "$GITHUB_SERVER_URL/Griefed" \
            --author-icon "https://i.griefed.de/images/2022/01/21/sam_1500x1500.th.jpg" \
            --image "https://i.griefed.de/images/2021/05/08/app.png" \
            --thumbnail "https://i.griefed.de/images/2020/11/18/Prosper_Docker_300x300.th.png" \
            --field "Author;[Griefed]($GITHUB_SERVER_URL/Griefed)" \
            --field "Platform;[GitHub]($GITHUB_SERVER_URL)" \
            --footer "Released at ${{ steps.date.outputs.today }}" \
            --footer-icon "https://i.griefed.de/images/2022/01/21/start_generation.png"
